#!/bin/bash

#################################################
##     NOTE THIS SCRIPT NO LONGER WORKS        ##
##      IT WAS ONLY USED FOR TIMING THE        ##
##                ORDERBOOK                    ##
#################################################

numOrders="$1"

sum=0.0
for i in {1..50}; do
    time=$(../build/engine "$numOrders")
    sum=$(echo "$sum + $time" | bc)
    i=$((i+1))
done

echo "$sum"